import Access from "../Portal/Access";
import { Localized } from "../i18n/Language";
import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, CheckCheck, LogOut, MessageCircle, Search, Send, Inbox as InboxIcon } from "lucide-react";
import { supabase } from "../lib/supabase";
import "./Inbox.css";
import { LanguageSwitch } from "../i18n/Language";
const channels = ["WhatsApp", "Instagram", "Facebook"];
const seed = [
  { id: 1, name: "Laura Martínez", company: "Clínica Vet Norte", channel: "WhatsApp", unread: true, status: "Pendiente", time: "10:42", messages: [{ text: "Hola, quisiera una página web para mi veterinaria. ¿Podemos hablar de los servicios?", own: false, time: "10:42" }] },
  { id: 2, name: "Andrés Gómez", company: "Estudio creativo", channel: "Instagram", unread: true, status: "Pendiente", time: "10:28", messages: [{ text: "Vi sus proyectos y me interesa automatizar las respuestas de mi negocio.", own: false, time: "10:28" }] },
  { id: 3, name: "Carolina Ruiz", company: "Tienda Carolina", channel: "Facebook", unread: false, status: "En curso", time: "09:56", messages: [{ text: "¿También desarrollan tiendas en línea?", own: false, time: "09:50" }, { text: "Sí, podemos ayudarte a definir el catálogo y el proceso de compra. ¿Qué productos vendes?", own: true, time: "09:56" }] },
  { id: 4, name: "Diego Torres", company: "Consultoría Torres", channel: "WhatsApp", unread: false, status: "Resuelto", time: "Ayer", messages: [{ text: "Gracias por la información. Ya tengo lo necesario para empezar.", own: false, time: "Ayer" }] },
];
export default function Inbox() {
  return <Access admin>{({ user }) => <Workspace key={user.id} user={user} />}</Access>;
}
function Workspace({ user }) {
  const [conversations, setConversations] = useState(seed);
  const [channel, setChannel] = useState("Todos"), [filter, setFilter] = useState("Todos"), [query, setQuery] = useState("");
  const [selected, setSelected] = useState(1), [mobileOpen, setMobileOpen] = useState(false), [drafts, setDrafts] = useState({});
  const [notice, setNotice] = useState(""), [signingOut, setSigningOut] = useState(false);
  const bottom = useRef(null);
  const current = conversations.find(c => c.id === selected);
  const draft = drafts[selected] || "";
  const visible = conversations.filter(c => (channel === "Todos" || c.channel === channel) && (filter === "Todos" || (filter === "Sin leer" ? c.unread : c.status === filter)) && `${c.name} ${c.company} ${c.messages.at(-1).text}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  useEffect(() => { bottom.current?.scrollIntoView({ block: "nearest" }); }, [selected, current.messages.length]);
  function open(c) { setSelected(c.id); setMobileOpen(true); setNotice(""); setConversations(all => all.map(item => item.id === c.id ? { ...item, unread: false } : item)); }
  function send(e) {
    e.preventDefault(); const text = draft.trim(); if (!text || text.length > 1500) return;
    const time = new Intl.DateTimeFormat("es-CO", { hour: "2-digit", minute: "2-digit" }).format(new Date());
    setConversations(all => all.map(c => c.id === selected ? { ...c, status: "En curso", unread: false, time, messages: [...c.messages, { own: true, text, time }] } : c));
    setDrafts(all => ({ ...all, [selected]: "" })); setNotice("Respuesta añadida a la demo. No se envió a ninguna red social.");
  }
  async function logout() { setSigningOut(true); try { const { error } = await supabase.auth.signOut(); if (error) throw error; } catch { setNotice("No pudimos cerrar sesión. Inténtalo nuevamente."); } finally { setSigningOut(false); } }
  return <Localized as="div" className="inbox-app">
    <Localized as="aside" className="inbox-nav"><Localized as={Link} className="inbox-brand" to="/"><Localized as="span">O.</Localized><Localized as="div">Ortegón<Localized as="small">Centro de mensajes</Localized></Localized></Localized><Localized as={Link} to="/panel">Volver al dashboard</Localized><Localized as="p" className="inbox-nav-label">ESPACIO DE TRABAJO</Localized><Localized as="div" className="inbox-nav-active"><InboxIcon size={18} /> Bandeja unificada</Localized><Localized as="p" className="inbox-nav-label">CANALES</Localized><Localized as="nav" aria-label="Filtrar por red social">{["Todos", ...channels].map(name => <Localized as="button" key={name} aria-pressed={channel === name} className={channel === name ? "active" : ""} onClick={() => { setChannel(name); setMobileOpen(false); }}><Localized as="span" className={`channel-dot ${name.toLowerCase()}`} />{name}<Localized as="b">{conversations.filter(c => (name === "Todos" || c.channel === name) && c.unread).length}</Localized></Localized>)}</Localized><Localized as="div" className="inbox-demo-note"><Localized as="strong">Tu próxima conexión</Localized><Localized as="p">Los tres canales están en modo demo. La integración con Meta llegará en la siguiente etapa.</Localized></Localized><Localized as="div" className="inbox-account"><Localized as="span" title={user.email}>{user.email}</Localized><Localized as="button" onClick={logout} disabled={signingOut}><LogOut size={16} />{signingOut ? "Saliendo…" : "Cerrar sesión"}</Localized></Localized></Localized>
    <Localized as="main" className="inbox-workspace"><Localized as="header" className="inbox-top"><Localized as="div"><Localized as="p">MENOS PESTAÑAS. MÁS CONVERSACIONES.</Localized><Localized as="h1">Tu bandeja, en un solo lugar.</Localized></Localized><LanguageSwitch /><Localized as="span" className="inbox-demo-badge">Demo · Sin conexiones reales</Localized></Localized>
    <Localized as="section" className={`inbox-grid ${mobileOpen ? "conversation-open" : ""}`} aria-label="Gestión de conversaciones">
      <Localized as="aside" className="inbox-list"><Localized as="div" className="inbox-list-heading"><Localized as="h2">Conversaciones <Localized as="span">{visible.length}</Localized></Localized><Localized as="p">{conversations.filter(c => c.unread).length} pendientes de lectura</Localized><Localized as="label" className="inbox-search"><Search size={17} /><Localized as="input" aria-label="Buscar conversaciones" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar nombre o mensaje" /></Localized><Localized as="select" aria-label="Filtrar por estado" value={filter} onChange={e => setFilter(e.target.value)}>{["Todos", "Sin leer", "Pendiente", "En curso", "Resuelto"].map(s => <Localized as="option" key={s}>{s}</Localized>)}</Localized></Localized><Localized as="div" className="inbox-conversations">{visible.length ? visible.map(c => <Localized as="button" key={c.id} className={`inbox-conversation ${selected === c.id ? "selected" : ""}`} onClick={() => open(c)} aria-pressed={selected === c.id}><Localized as="span" className="inbox-avatar">{c.name.split(" ").map(n => n[0]).join("")}</Localized><Localized as="div"><Localized as="div" className="inbox-conversation-title"><Localized as="strong">{c.name}</Localized><Localized as="small">{c.time}</Localized></Localized><Localized as="p" translate="no">{c.messages.at(-1).text}</Localized><Localized as="span" className={`channel-tag ${c.channel.toLowerCase()}`}>{c.channel}</Localized>{c.unread && <Localized as="i" aria-label="Sin leer" />}</Localized></Localized>) : <Localized as="div" className="inbox-empty"><Search /><Localized as="h3">No hay coincidencias</Localized><Localized as="p">Prueba otro nombre, canal o estado.</Localized><Localized as="button" onClick={() => { setChannel("Todos"); setFilter("Todos"); setQuery(""); }}>Limpiar filtros</Localized></Localized>}</Localized></Localized>
      <Localized as="section" className="inbox-thread" aria-label={`Conversación con ${current.name}`}><Localized as="header" className="inbox-thread-header"><Localized as="button" className="inbox-back" aria-label="Volver a conversaciones" onClick={() => setMobileOpen(false)}><ArrowLeft size={20} /></Localized><Localized as="span" className="inbox-avatar">{current.name.split(" ").map(n => n[0]).join("")}</Localized><Localized as="div"><Localized as="h2">{current.name}</Localized><Localized as="span" className={`channel-tag ${current.channel.toLowerCase()}`}>{current.channel}</Localized></Localized><Localized as="label" className="inbox-status">Estado<Localized as="select" value={current.status} onChange={e => setConversations(all => all.map(c => c.id === selected ? { ...c, status: e.target.value } : c))}>{["Pendiente", "En curso", "Resuelto"].map(s => <Localized as="option" key={s}>{s}</Localized>)}</Localized></Localized></Localized><Localized as="div" className="inbox-messages"><Localized as="p" className="inbox-day">Conversación de demostración</Localized>{current.messages.map((m, i) => <Localized as="div" key={i} className={`inbox-bubble ${m.own ? "own" : ""}`}><Localized as="p" translate="no">{m.text}</Localized><Localized as="small">{m.time} {m.own && <CheckCheck size={13} aria-label="Guardado en la demo" />}</Localized></Localized>)}<Localized as="div" ref={bottom} /></Localized><Localized as="form" className="inbox-compose" onSubmit={send}><Localized as="label" htmlFor="inbox-reply">Responder en la demo</Localized><Localized as="textarea" id="inbox-reply" placeholder={`Escribe una respuesta para ${current.name.split(" ")[0]}…`} value={draft} maxLength={1500} onChange={e => setDrafts(all => ({ ...all, [selected]: e.target.value }))} /><Localized as="div"><Localized as="small">{draft.length}/1500 · Se borra al recargar</Localized><Localized as="button" disabled={!draft.trim()} type="submit">Añadir respuesta <Send size={16} /></Localized></Localized><Localized as="p" role="status">{notice || "Ningún mensaje de esta pantalla se envía a WhatsApp, Instagram o Facebook."}</Localized></Localized></Localized>
      <Localized as="aside" className="inbox-details"><Localized as="p" className="inbox-nav-label">INFORMACIÓN DEL CONTACTO</Localized><Localized as="span" className="inbox-avatar large">{current.name.split(" ").map(n => n[0]).join("")}</Localized><Localized as="h2">{current.name}</Localized><Localized as="p">{current.company}</Localized><Localized as="dl"><Localized as="dt">Canal de origen</Localized><Localized as="dd">{current.channel}</Localized><Localized as="dt">Estado</Localized><Localized as="dd">{current.status}</Localized><Localized as="dt">Responsable</Localized><Localized as="dd">Mi bandeja</Localized></Localized><Localized as="div" className="inbox-detail-note"><MessageCircle size={20} /><Localized as="h3">Todo el contexto, a mano.</Localized><Localized as="p">Aquí se integrarán los datos reales del contacto cuando conectemos cada canal.</Localized></Localized></Localized>
    </Localized></Localized></Localized>;
}
