import { Link } from "react-router-dom";
import { Code2, Workflow, BrainCircuit, ArrowUpRight } from "lucide-react";
import { Localized, useLanguage } from "../i18n/Language";
const capabilities = [
 { Icon: Code2, es: ["Experiencias digitales", "Interfaces claras y plataformas preparadas para crecer. Elegimos la tecnología según tu proyecto, no al revés."], en: ["Digital experiences", "Clear interfaces and platforms ready to grow. We choose technology to fit your project, not the other way around."], tech: ["React", "Node.js", "Tailwind", "Vite"] },
 { Icon: Workflow, es: ["Operaciones conectadas", "Conectamos herramientas y automatizamos tareas repetitivas para que tu equipo pueda concentrarse en lo importante."], en: ["Connected operations", "We connect tools and automate repetitive tasks so your team can focus on what matters."], tech: ["n8n", "Supabase", "Firebase", "Zoho"] },
 { Icon: BrainCircuit, es: ["Inteligencia aplicada", "Asistentes y soluciones con IA que responden a una necesidad concreta de tu negocio."], en: ["Applied intelligence", "AI assistants and solutions built around a specific business need."], tech: ["OpenAI", "Python", "WhatsApp"] },
];
export default function Stack() {
 const { language } = useLanguage(); const english = language === "en";
 return <Localized as="section" id="stack" className="editorial-section technology-section"><Localized as="div" className="editorial-container"><Localized as="div" className="editorial-heading"><Localized as="div"><Localized as="p" className="editorial-kicker">{english ? "02 / OUR APPROACH" : "02 / NUESTRA FORMA DE HACERLO"}</Localized><Localized as="h2">{english ? "Good technology.\nA clear purpose." : "Buena tecnología.\nUn propósito claro."}</Localized></Localized><Localized as="p">{english ? "A thoughtful combination of software, automation and AI. Built around what your business actually needs." : "Una combinación de software, automatización e IA, pensada alrededor de lo que tu negocio realmente necesita."}</Localized></Localized><Localized as="div" className="capability-grid">{capabilities.map(({ Icon, es, en, tech }, index) => { const copy = english ? en : es; return <Localized as="article" className="capability-card" key={es[0]}><Localized as="div" className="capability-top"><Icon size={24} strokeWidth={1.5}/><Localized as="span">0{index + 1}</Localized></Localized><Localized as="h3">{copy[0]}</Localized><Localized as="p">{copy[1]}</Localized><Localized as="div" className="technology-labels">{tech.map(name => <Localized as="span" key={name}>{name}</Localized>)}</Localized></Localized>; })}</Localized><Localized as={Link} className="editorial-link" to="/cotizar">{english ? "Let's find the right solution" : "Encontremos la solución adecuada"}<ArrowUpRight size={17}/></Localized></Localized></Localized>;
}
