import { ArrowUpRight, Globe, Layers, Hand } from "lucide-react";
import { Localized, useLanguage } from "../i18n/Language";
const projects = [
 { name: "Blurealty.AI", category: ["Inmobiliaria · Plataforma web", "Real estate · Web platform"], description: ["Una experiencia digital que conecta la búsqueda inmobiliaria con herramientas de inteligencia artificial.", "A digital experience connecting real estate search with artificial intelligence tools."], tags: ["React", "Zoho", "Firebase"], href: "https://blurealty.ai/", Icon: Globe, status: ["Beta", "Beta"] },
 { name: "5IG Solutions", category: ["Servicios · Presencia digital", "Services · Digital presence"], description: ["Una presentación web para comunicar servicios tecnológicos y facilitar el contacto con nuevos clientes.", "A web presence to communicate technology services and help new customers get in touch."], tags: ["React", "Node.js", "Azure"], href: "https://5igsolutions.com/", Icon: Layers, status: ["Publicado", "Published"] },
 { name: "enSEÑArte LSC", category: ["Educación · Lengua de señas", "Education · Sign language"], description: ["Tecnología aplicada al aprendizaje de la lengua de señas colombiana, con una plataforma web como punto de encuentro.", "Technology applied to Colombian Sign Language learning, with a web platform as the meeting point."], tags: ["React", "Firebase", "Docker"], href: "https://www.linkedin.com/feed/update/urn:li:activity:7346741868321288192/", Icon: Hand, status: ["Beta", "Beta"] },
];
const docs = { React: "https://react.dev/", Zoho: "https://www.zoho.com/developer/", Firebase: "https://firebase.google.com/docs", "Node.js": "https://nodejs.org/en/docs", Azure: "https://learn.microsoft.com/azure/", Docker: "https://docs.docker.com/" };
export default function Projects() {
 const { language } = useLanguage(); const n = language === "en" ? 1 : 0;
 return <Localized as="section" id="projects" className="editorial-section selected-projects"><Localized as="div" className="editorial-container"><Localized as="div" className="editorial-heading"><Localized as="div"><Localized as="p" className="editorial-kicker">{n ? "03 / SELECTED WORK" : "03 / PROYECTOS SELECCIONADOS"}</Localized><Localized as="h2">{n ? "Ideas that became\nreal projects." : "Ideas que se convirtieron\nen proyectos reales."}</Localized></Localized><Localized as="p">{n ? "Different industries. Different challenges. A shared approach: useful, carefully built technology." : "Sectores distintos. Retos diferentes. Una misma forma de trabajar: tecnología útil, construida con cuidado."}</Localized></Localized><Localized as="div" className="selected-project-grid">{projects.map(({ name, category, description, tags, href, Icon, status }, index) => <Localized as="article" className="selected-project-card" key={name}><Localized as="a" className={`project-cover project-cover-${index}`} href={href} target="_blank" rel="noopener noreferrer" aria-label={`${n ? "Open project" : "Abrir proyecto"}: ${name}`}><Localized as="span" className="project-status">{status[n]}</Localized><Icon className="project-symbol" size={64} strokeWidth={1}/><Localized as="strong">{name}</Localized><Localized as="span" className="project-open"><ArrowUpRight size={20}/></Localized></Localized><Localized as="div" className="project-editorial-copy"><Localized as="p" className="project-category">{category[n]}</Localized><Localized as="h3">{name}</Localized><Localized as="p">{description[n]}</Localized><Localized as="div" className="project-tech-links">{tags.map(tag => <Localized as="a" key={tag} href={docs[tag]} target="_blank" rel="noopener noreferrer" title={`${n ? "Documentation" : "Documentación"}: ${tag}`}>{tag}<ArrowUpRight size={11}/></Localized>)}</Localized><Localized as="a" className="editorial-link" href={href} target="_blank" rel="noopener noreferrer">{index === 2 ? (n ? "Explore the project" : "Conocer el proyecto") : (n ? "Visit website" : "Visitar sitio")}<ArrowUpRight size={16}/></Localized></Localized></Localized>)}</Localized></Localized></Localized>;
}
